Repository FairyProject/fairy, pull requests merged in 2021-12, with the labels that each got.

#6 Reflection and NMS updates, some fixes
  gradle.properties
  io.fairyproject.modules/module.command/bukkit-command/src/main/java/io/fairyproject/bukkit/command/BukkitCommandListener.java
  io.fairyproject.modules/module.command/bukkit-command/src/main/java/io/fairyproject/bukkit/command/util/CommandUtil.java
  io.fairyproject.modules/module.storage/core-storage/src/main/java/io/fairyproject/StorageService.java
  io.fairyproject.modules/platform.core/core-legacy/build.gradle
  io.fairyproject.modules/platform.core/core-legacy/src/main/java/io/fairyproject/redis/RedisService.java
  io.fairyproject.modules/platform.core/core-legacy/src/main/resources/redisson.yml
  io.fairyproject.modules/platform.mc/module.bossbar/bukkit-bossbar/src/main/java/io/fairyproject/bukkit/bossbar/BossBar.java
  io.fairyproject.platforms/bukkit-platform/build.gradle
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/FairyBukkitPlatform.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/impl/server/NormalImplementation.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCPlayer.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCServer.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/protocol/BukkitNettyInjector.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/MinecraftReflection.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/minecraft/DataWatcher.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/minecraft/MinecraftVersion.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/resolver/minecraft/NMSClassResolver.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/resolver/minecraft/OBCClassResolver.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/version/protocol/ProtocolCheckFieldVersion.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/version/protocol/ProtocolCheckMethodVersion.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/wrapper/ChatComponentWrapper.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/library/Library.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/library/LibraryHandler.java
Labels: enhancement

#7 Application platform fix and structure improvement
  build.gradle
  buildSrc/src/main/java/io/fairyproject/gradle/ModuleExtension.java
  buildSrc/src/main/java/io/fairyproject/gradle/ModulePlugin.java
  gradle-plugin/build.gradle
  gradle/bootstrap.gradle
  gradle/builder.gradle
  gradle/module.gradle
  io.fairyproject.bootstraps/app-bootstrap/src/main/java/io/fairyproject/bootstrap/app/AppBootstrap.java
  io.fairyproject.bootstraps/app-bootstrap/src/main/java/io/fairyproject/bootstrap/app/AppLauncher.java
  io.fairyproject.bootstraps/app-bootstrap/src/main/java/io/fairyproject/bootstrap/app/ApplicationAction.java
  io.fairyproject.modules/module.command/core-command/build.gradle
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandContext.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandMeta.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/ICommand.java
  io.fairyproject.modules/module.discord/build.gradle
  io.fairyproject.modules/module.discord/src/main/java/io/fairyproject/discord/DCBot.java
  io.fairyproject.modules/module.discord/src/main/java/io/fairyproject/discord/command/DCCommandContext.java
  io.fairyproject.modules/module.discord/src/main/java/io/fairyproject/discord/command/DCCommandListener.java
  io.fairyproject.modules/module.discord/src/main/java/io/fairyproject/discord/command/DCCommandMap.java
  io.fairyproject.platforms/app-platform/src/main/java/io/fairyproject/app/Application.java
  io.fairyproject.platforms/app-platform/src/main/java/io/fairyproject/app/FairyAppPlatform.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/ContainerContext.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/Module.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleService.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/controller/ExclusiveController.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/bean/ServiceTest.java
Labels: enhancement

#12 Updated log4j to 2.15.0
  build.gradle
  gradle.properties
  io.fairyproject.bootstraps/app-bootstrap/build.gradle
Labels: enhancement

#10 Made sidebar module mc-universal
  io.fairyproject.modules/platform.mc/module.sidebar/build.gradle
  io.fairyproject.modules/platform.mc/module.sidebar/bukkit-sidebar/.gitignore
  io.fairyproject.modules/platform.mc/module.sidebar/bukkit-sidebar/build.gradle
  io.fairyproject.modules/platform.mc/module.sidebar/bukkit-sidebar/src/main/java/io/fairyproject/bukkit/sidebar/Sidebar.java
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/Sidebar.java
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/SidebarAdapter.java
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/SidebarService.java
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/SidebarTeam.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/MCProtocol.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/item/ObjectiveDisplaySlot.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/item/ObjectiveRenderType.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/item/ScoreAction.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/mapping/MCProtocolMapping1_8.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/netty/FriendlyByteBuf.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/packet/PacketPlay.java
  settings.gradle
Labels: enhancement, size/XL

#17 Make timer uses Adventure api
  io.fairyproject.modules/platform.bukkit/bukkit-timer/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-timer/src/main/java/io/fairyproject/bukkit/timer/Timer.java
Labels: enhancement, size/M
