Repository FairyProject/fairy, pull requests merged in 2022-03, with the labels that each got.

#46 [ci skip] Removed FAWE repository
  build.gradle
Labels: bug

#43 Reflection game profile bug fix
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/MinecraftReflection.java
Labels: bug, size/S

#45 Ported to PacketEvents API
  build.gradle
  gradle-plugin/build.gradle
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyExtension.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyPlugin.java
  gradle.properties
  gradle/builder.gradle
  gradle/tasks.gradle
  gradle/wrapper/gradle-wrapper.properties
  io.fairyproject.modules/module.command/bukkit-command/src/main/java/io/fairyproject/bukkit/command/parameters/GameModeArgTransformer.java
  io.fairyproject.modules/module.locale/mc-locale/build.gradle
  io.fairyproject.modules/module.locale/mc-locale/src/main/java/io/fairyproject/locale/Locales.java
  io.fairyproject.modules/platform.mc/module.bossbar/bukkit-bossbar/build.gradle
  io.fairyproject.modules/platform.mc/module.nametag/build.gradle
  io.fairyproject.modules/platform.mc/module.nametag/src/main/java/io/fairyproject/mc/nametag/NameTagService.java
  io.fairyproject.modules/platform.mc/module.sidebar/build.gradle
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/Sidebar.java
  io.fairyproject.modules/platform.mc/module.tablist/build.gradle
  io.fairyproject.modules/platform.mc/module.tablist/src/main/java/io/fairyproject/mc/tablist/Tablist.java
  io.fairyproject.modules/platform.mc/module.tablist/src/main/java/io/fairyproject/mc/tablist/util/impl/MainTablistImpl.java
  io.fairyproject.platforms/bukkit-platform/build.gradle
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/FairyBukkitPlatform.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCInitializer.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/library/LibraryHandler.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/util/FileUtil.java
  io.fairyproject.platforms/mc-platform/build.gradle
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCAdventure.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCInitializer.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCPlayer.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/MCProtocol.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/mapping/MCProtocolMapping.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/mapping/MCProtocolMapping1_8.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/packet/PacketDeserializer.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/packet/PacketPlay.java
  io.fairyproject.tests/mc-tests/src/main/java/io/fairyproject/tests/mc/MCPlayerMock.java
  settings.gradle
  test-plugin/build.gradle
  test-plugin/src/main/java/io/fairyproject/debug/DebugPlugin.java
Labels: enhancement, size/XXL

#50 Fixed ModuleService not being initialized properly during unit testing phase
  io.fairyproject.tests/core-tests/src/main/java/io/fairyproject/tests/FairyTestingPlatform.java
  io.fairyproject.tests/core-tests/src/main/java/io/fairyproject/tests/TestingBase.java
Labels: bug, size/M

#48 MySQL storage boolean reading fix and stacktrace printing
  io.fairyproject.modules/module.locale/parent.gradle
  io.fairyproject.modules/module.storage/core-storage/src/main/java/io/fairyproject/SQLRepository.java
  io.fairyproject.modules/module.storage/core-storage/src/main/java/io/fairyproject/mysql/pojo/statement/MySqlStatementBuilder.java
  io.fairyproject.modules/module.storage/parent.gradle
Labels: size/S

#52 Fixed a bug where PlayerOnlineValue recursively trying to find MCPlayer even when null
  build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-menu/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-timer/build.gradle
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/metadata/PlayerOnlineValue.java
Labels: bug, size/S

#49 Improved Serializers
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/ObjectSerializer.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/SerializerFactory.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/SerializerJacksonConfigure.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/jackson/JacksonObjectDeserializer.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/jackson/JacksonObjectSerializer.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/serializer/AvoidDuplicate.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/serializer/SerializerData.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/serializer/ObjectSerializerAvoidDuplicationMock.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/serializer/ObjectSerializerMock.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/serializer/SerializerFactoryTest.java
Labels: documentation, enhancement, size/L

#51 Debug environment improvements
  build.gradle
  buildSrc/src/main/java/io/fairyproject/gradle/ModuleTask.java
  gradle-plugin/build.gradle
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyExtension.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/util/MavenUtil.java
  gradle-plugin/src/test/java/io/fairytest/gradle/MavenUtilTest.java
  gradle.properties
  gradle/basic.gradle
  gradle/bootstrap.gradle
  gradle/builder.gradle
  gradle/publish.gradle
  gradle/tasks.gradle
  io.fairyproject.bootstraps/bootstrap/src/main/java/io/fairyproject/bootstrap/util/DownloadUtil.java
  io.fairyproject.bootstraps/bukkit-bootstrap/src/main/java/io/fairyproject/bootstrap/bukkit/BukkitPlugin.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandService.java
  io.fairyproject.modules/module.command/parent.gradle
  io.fairyproject.modules/platform.mc/module.sidebar/build.gradle
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/Sidebar.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/FairyBukkitPlatform.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCInitializer.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/util/PlayerLocaleUtil.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/util/nms/NBTEditor.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/Debug.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/FairyPlatform.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/ContainerContext.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/scanner/ClassPathScanner.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/scanner/ThreadedClassPathScanner.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/Module.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleDownloader.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModulePluginListenerAdapter.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleService.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/controller/ExclusiveController.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/reflect/ReflectLookup.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/util/PreProcessBatch.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/util/thread/BlockingThreadAwaitQueue.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/container/ContainerTest.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/container/service/ServiceMock.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/container/threaded/ThreadedClassPathScannerTest.java
  io.fairyproject.platforms/mc-platform/build.gradle
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCAdventure.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCInitializer.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCPlayer.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/MCProtocol.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/packet/PacketPlay.java
  scripts/Debug.run.xml
  settings.gradle
  test-plugin/build.gradle
  test-plugin/src/main/java/io/fairyproject/debug/DebugPlugin.java
  test-plugin/src/main/java/io/fairyproject/debug/DebugService.java
  test-plugin/src/main/java/io/fairyproject/debug/IDE.java
Labels: bug, enhancement, size/XXL

#55 Fixed ItemBuilder + added unbreakable thing
  io.fairyproject.modules/platform.bukkit/bukkit-items/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/ItemBuilder.java
  io.fairyproject.modules/platform.bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/ItemSet.java
Labels: size/S

#47 Command improvement and bug fixes
  io.fairyproject.modules/module.command/bukkit-command/src/main/java/io/fairyproject/bukkit/command/BukkitCommandExecutor.java
  io.fairyproject.modules/module.command/bukkit-command/src/main/java/io/fairyproject/bukkit/command/event/BukkitCommandContext.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommandInitializer.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandMeta.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/ICommand.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/annotation/Command.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/annotation/Order.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/annotation/Usage.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/completion/ArgCompletionHolderList.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/completion/ArgCompletionHolderStringArray.java
  io.fairyproject.modules/module.command/parent.gradle
Labels: bug, enhancement, size/XL

#57 New versioning system
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-snapshot.yml
  .github/workflows/pr.yml
  build.gradle
  buildSrc/src/main/java/io/fairyproject/gradle/FairyVersion.java
  gradle-plugin/build.gradle
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyPlugin.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/util/FairyVersion.java
  gradle/publish.gradle
  io.fairyproject.platforms/core-platform/build.gradle
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModulePluginListenerAdapter.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleService.java
  settings.gradle
  shared/.gitignore
  shared/build.gradle
  shared/src/main/java/io/fairyproject/shared/FairyVersion.java
  shared/src/test/java/io/fairytest/FairyVersionTest.java
Labels: enhancement, size/L

#58 Fixed wrong version usage in compiled module json
  .github/workflows/deploy-snapshot.yml
  buildSrc/src/main/java/io/fairyproject/gradle/ModulePlugin.java
  buildSrc/src/main/java/io/fairyproject/gradle/ModuleTask.java
  buildSrc/src/main/java/io/fairyproject/gradle/PublishSnapshotTask.java
  gradle/publish.gradle
Labels: bug, size/M

#61 Added support for NestedConfig
  io.fairyproject.modules/module.config/src/main/java/io/fairyproject/config/annotation/NestedConfig.java
  io.fairyproject.modules/module.config/src/main/java/io/fairyproject/config/filter/FieldFilter.java
  io.fairyproject.modules/module.config/src/main/java/io/fairyproject/config/yaml/YamlConfiguration.java
  io.fairyproject.modules/module.config/src/test/java/io/fairytest/config/filter/DummyClassA.java
  io.fairyproject.modules/module.config/src/test/java/io/fairytest/config/filter/DummyClassB.java
  io.fairyproject.modules/module.config/src/test/java/io/fairytest/config/filter/DummyClassC.java
  io.fairyproject.modules/module.config/src/test/java/io/fairytest/config/filter/FieldFilterTest.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleDownloader.java
Labels: enhancement, size/L

#63 Fixed a problem where gradle plugin cannot be published
  gradle-plugin/build.gradle
  gradle/builder.gradle
  shared/build.gradle
Labels: bug

#65 Fixed sidebar title display incorrectly in 1.12 and below
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/Sidebar.java
Labels: bug

#66 Fixed command on usage display, argument analyse and tab complete with enum
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandMeta.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandService.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/scanner/BaseClassPathScanner.java
Labels: bug

#67 Added timings support to BukkitTaskScheduler
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/impl/BukkitTaskScheduler.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/task/ITaskScheduler.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/task/Task.java
Labels: enhancement, size/L

#62 Added ActionBar module
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyExtension.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/FairyPlugin.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/util/MavenUtil.java
  io.fairyproject.modules/platform.mc/module.actionbar/.gitignore
  io.fairyproject.modules/platform.mc/module.actionbar/build.gradle
  io.fairyproject.modules/platform.mc/module.actionbar/src/main/java/io/fairyproject/mc/actionbar/ActionbarAdapter.java
  io.fairyproject.modules/platform.mc/module.actionbar/src/main/java/io/fairyproject/mc/actionbar/ActionbarService.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/Containers.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/module/ModuleService.java
  settings.gradle
Labels: enhancement, size/L

#68 Added no arg command support
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommandInitializer.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/annotation/Command.java
Labels: enhancement, size/M

#69 Improved OBCVersion and made publishSnapshotTasks works on every subprojects
  build.gradle
  buildSrc/src/main/java/io/fairyproject/gradle/ModulePlugin.java
  buildSrc/src/main/java/io/fairyproject/gradle/PublishSnapshotTask.java
  gradle-plugin/src/main/java/io/fairyproject/gradle/util/MavenUtil.java
  io.fairyproject.modules/platform.mc/module.hologram/bukkit-hologram/src/main/java/io/fairyproject/bukkit/hologram/HologramSingle.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/FairyBukkitPlatform.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/MinecraftReflection.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/annotation/Class.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/annotation/Field.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/annotation/Method.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/annotation/ReflectionAnnotations.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/minecraft/DataWatcher.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/minecraft/MinecraftVersion.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/minecraft/OBCVersion.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/resolver/minecraft/NMSClassResolver.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/reflection/version/protocol/ProtocolCheckNone.java
  io.fairyproject.platforms/bukkit-platform/src/test/java/io/fairytest/OBCVersionTest.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/MCProtocol.java
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/protocol/MCVersion.java
  io.fairyproject.tests/bukkit-tests/src/main/java/io/fairyproject/tests/bukkit/FairyBukkitTestingPlatform.java
  shared/src/main/java/io/fairyproject/shared/FairyVersion.java
Labels: bug, enhancement, size/XL
