Repository FairyProject/fairy, pull requests merged in 2022-04, with the labels that each got.

#72 Fix ItemBuilder#unbreakable
  io.fairyproject.modules/platform.bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/ItemBuilder.java
Labels: bug, size/XS

#73 Minor bug fixes
  gradle-plugin/build.gradle
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandMeta.java
  io.fairyproject.modules/platform.mc/module.nametag/src/main/java/io/fairyproject/mc/nametag/NameTagService.java
  io.fairyproject.modules/platform.mc/module.tablist/src/main/java/io/fairyproject/mc/tablist/Tablist.java
Labels: bug, size/M

#74 Improved Visual module implementation
  gradle.properties
  io.fairyproject.modules/platform.bukkit/bukkit-visual/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/VisualBlock.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/VisualBlockService.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/VisualPosition.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/VisualTask.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/type/MaterialVisualType.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/type/VisualType.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/util/BlockPositionData.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/util/VisualContainer.java
  io.fairyproject.modules/platform.bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/util/VisualUtil.java
  io.fairyproject.platforms/bukkit-platform/build.gradle
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/impl/server/NormalImplementation.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCWorld.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/util/BlockPositionData.java
  io.fairyproject.platforms/mc-platform/build.gradle
  io.fairyproject.platforms/mc-platform/src/main/java/io/fairyproject/mc/MCWorld.java
Labels: bug, enhancement, size/XL
