Repository FairyProject/fairy, pull requests merged in 2023-07, with the labels that each got.

#99 fix: Fix NBT Editor by updating for 1.20 compat
  io.fairyproject.modules/platform.bukkit/bukkit-nbt/src/main/java/io/fairyproject/bukkit/nbt/nms/NBTEditor.java
Labels: size/L

#100 fix: Update packetevents to 2.0 github
  gradle/libs.versions.toml
  io.fairyproject.modules/platform.mc/module.hologram/src/main/java/io/fairyproject/mc/hologram/HologramImpl.java
  io.fairyproject.tests/mc-tests/src/main/java/io/fairyproject/tests/mc/protocol/MockChannelOperator.java
Labels: size/S

#103 v0.6.5b2
  gradle.properties
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/src/main/java/com/cryptomorin/xseries/XBlock.java
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/src/main/java/io/fairyproject/bukkit/xseries/XMaterialSerializer.java
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/src/main/java/io/fairyproject/bukkit/xseries/XSoundSerializer.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/timings/TimingService.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/controller/AutowiredContainerController.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/util/AccessUtil.java
Labels: size/L

#105 MenuNode system
  gradle.properties
  io.fairyproject.modules/module.command/core-command/src/main/java/io/fairyproject/command/CommandMeta.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/Menu.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/event/ButtonClickEvent.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/event/MenuCloseEvent.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/MenuNode.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/MenuNodeImpl.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/condition/ClickCondition.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/condition/CloseCondition.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/condition/Condition.java
  io.fairyproject.modules/platform.bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/node/condition/ConditionTarget.java
Labels: enhancement, size/XL
