Repository FairyProject/fairy, pull requests merged in 2024-07, with the labels that each got.

#155 Updated to 1.21 support
  .github/workflows/build.yml
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/composite/PublishTaskHolder.kt
  build-logic/src/main/kotlin/composite/io.fairyproject.composite.builds.gradle.kts
  build-logic/src/main/kotlin/composite/io.fairyproject.composite.subprojects.gradle.kts
  build-logic/src/main/kotlin/io.fairyproject.common.gradle.kts
  build-logic/src/main/kotlin/io.fairyproject.module.bukkit.gradle.kts
  framework/bootstraps/bukkit-bootstrap/build.gradle.kts
  framework/bootstraps/bukkit-bootstrap/src/test/java/io/fairyproject/bootstrap/bukkit/BukkitPluginTest.java
  framework/devtools/bukkit-devtools/build.gradle.kts
  framework/devtools/core-devtools/build.gradle.kts
  framework/modules/bukkit/bukkit-command/src/main/java/io/fairyproject/bukkit/command/parameters/GameModeArgTransformer.java
  framework/modules/bukkit/bukkit-command/src/main/java/io/fairyproject/bukkit/command/parameters/PlayerParameterTransformer.java
  framework/modules/bukkit/bukkit-command/src/main/java/io/fairyproject/bukkit/command/parameters/WorldParameterTransformer.java
  framework/modules/bukkit/bukkit-command/src/main/java/io/fairyproject/bukkit/command/util/CommandUtil.java
  framework/modules/bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/pane/PaginatedPane.java
  framework/modules/bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/pane/mapping/OutlinePaneMapping.java
  framework/modules/bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/pane/mapping/StaticPaneMapping.java
  framework/modules/bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/impl/ItemBuilderImpl.java
  framework/modules/bukkit/bukkit-nbt/build.gradle.kts
  framework/modules/bukkit/bukkit-xseries/build.gradle.kts
  framework/modules/bukkit/bukkit-xseries/src/main/java/com/cryptomorin/xseries/XBlock.java
  framework/modules/core/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  framework/modules/core/core-command/src/main/java/io/fairyproject/command/BaseCommandInitializer.java
  framework/modules/mc/mc-hologram/src/main/java/io/fairyproject/mc/hologram/HologramImpl.java
  framework/modules/mc/mc-nametag/src/main/java/io/fairyproject/mc/nametag/NameTagService.java
  framework/modules/mc/mc-sidebar/src/main/java/io/fairyproject/sidebar/SidebarService.java
  framework/platforms/bukkit-platform/build.gradle.kts
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/version/BukkitVersionDecoderImpl.java
  framework/platforms/bukkit-platform/src/test/java/io/fairyproject/bukkit/plugin/impl/ClassLoaderJavaPluginIdentifierTest.java
  framework/platforms/bukkit-platform/src/test/java/io/fairyproject/bukkit/version/BukkitVersionDecoderImplTest.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/FairyPlatform.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/collection/ContainerObjCollectorImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/collection/ContainerObjCollectorRegistry.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/library/relocate/RelocationHandlerImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/scheduler/executor/ExecutorScheduler.java
  framework/platforms/mc-platform/build.gradle.kts
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/version/impl/MCVersionImpl.java
  framework/platforms/mc-platform/src/test/java/io/fairyproject/mc/version/MCVersionImplTest.java
  framework/tests/bukkit-tests/build.gradle.kts
  framework/tests/mc-tests/src/main/java/io/fairyproject/tests/mc/protocol/MockByteBufOperator.java
  global.properties
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/extension/property/Properties.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/FairyResourceAction.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/impl/FairyResourceBukkitMeta.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/runner/RunServerPlugin.kt
  scripts/Debug.run.xml
  test-plugin/build.gradle.kts
Labels: size/L

#157 feat: make player damage events call on highest priority,
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/listener/impl/CallEventListener.java
Labels: size/XS

#158 Don't redownload MCVersionMapping every start when unnecessary
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/version/MCVersionMappingRegistry.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/version/cache/MCVersionMappingCache.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/version/cache/MCVersionMappingCacheImpl.java
  framework/platforms/mc-platform/src/test/java/io/fairyproject/mc/version/MCVersionMappingRegistryTest.java
Labels: enhancement, size/L

#159 Added MetaStorage to replace MetadataMap
  framework/modules/bukkit/bukkit-command/src/main/java/io/fairyproject/bukkit/command/map/DefaultBukkitCommandMap.java
  framework/modules/bukkit/bukkit-command/src/test/java/io/fairyproject/command/map/DefaultBukkitCommandMapTest.java
  framework/modules/bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/Gui.java
  framework/modules/bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/FairyItem.java
  framework/modules/bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/behaviour/ItemBehaviourBlockMarker.java
  framework/modules/bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/impl/FairyItemImpl.java
  framework/modules/bukkit/bukkit-menu/src/main/java/io/fairyproject/bukkit/menu/Menu.java
  framework/modules/bukkit/bukkit-visual/src/main/java/io/fairyproject/bukkit/visual/sender/VisualBlockSender.java
  framework/modules/core/core-command/src/main/java/io/fairyproject/command/BaseCommand.java
  framework/modules/core/core-command/src/main/java/io/fairyproject/command/BaseCommandInitializer.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/FairyBukkitPlatform.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCEntity.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCPlayer.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMCWorld.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/BukkitMetadataBridge.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/registry/BukkitMCWorldRegistry.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/metadata/package-info.java
  framework/platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/plugin/BukkitPluginHandler.java
  framework/platforms/core-platform/build.gradle.kts
  framework/platforms/core-platform/src/jmh/java/io/fairyproject/data/impl/MetaStorageImplBenchmark.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/ContainerObj.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/ContainerObjImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/processor/injection/SubscribeEventAnnotationProcessor.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/MetaKey.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/MetaRegistry.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/MetaStorage.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/MetaKeyImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/MetaRegistryImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/MetaStorageImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/collection/MetaCollectionKey.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/collection/MetaListKey.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/collection/MetaMapKey.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/data/impl/collection/MetaSetKey.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/metadata/CommonMetadataRegistries.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/metadata/package-info.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/util/TypeLiteral.java
  framework/platforms/core-platform/src/test/java/io/fairyproject/data/impl/MetaStorageImplTest.java
  framework/platforms/core-platform/src/test/java/io/fairyproject/scheduler/executor/RepeatedExecutorScheduledTaskTest.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/MCPlayer.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/MCWorld.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/data/MCMetadata.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/data/MCMetadataBridge.java
  framework/platforms/mc-platform/src/main/java/io/fairyproject/mc/metadata/PlayerOnlineValue.java
  framework/tests/mc-tests/src/main/java/io/fairyproject/tests/mc/MCPlayerMock.java
  global.properties
Labels: enhancement, size/XXL
