Repository FairyProject/fairy, pull requests merged in 2024-03, with the labels that each got.

#133 fix: Fixed bukkit-yml not properly generating when bukkit-bootstrap exists
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/impl/FairyResourceBukkitMeta.kt
  gradle.properties
Labels: size/S

#135 fix: Add method for exact class binding retrieval
  gradle.properties
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/binder/ContainerObjectBinder.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/binder/ContainerObjectBinderImpl.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/node/scanner/ContainerNodeClassScanner.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/node/scanner/ContainerNodeConfigurationScanner.java
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/node/scanner/ContainerNodeLegacyScanner.java
  io.fairyproject.platforms/core-platform/src/test/java/io/fairyproject/container/binder/ContainerObjectBinderImplTest.java
Labels: size/S

#136 fix(gradle-plugin): Avoid taking module-info as the main class
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/FairyResourceAction.kt
  gradle.properties
Labels: bug, size/XS

#139 Sidebar Improvements
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/Sidebar.java
  io.fairyproject.modules/platform.mc/module.sidebar/src/main/java/io/fairyproject/sidebar/SidebarService.java
Labels: size/M

#138 feat: Add exception handling in TimerService scheduling
  io.fairyproject.modules/platform.bukkit/bukkit-timer/src/main/java/io/fairyproject/bukkit/timer/TimerService.java
Labels: size/S

#141 Fixed many dependency issues
  gradle/libs.versions.toml
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/build.gradle
  io.fairyproject.modules/platform.bukkit/bukkit-xseries/src/main/java/com/cryptomorin/xseries/XSound.java
  io.fairyproject.platforms/bukkit-platform/build.gradle
  io.fairyproject.platforms/core-platform/src/main/java/io/fairyproject/container/node/scanner/ContainerNodeLegacyScanner.java
  io.fairyproject.platforms/mc-platform/build.gradle
Labels: size/XXL

#142 Fixed Data Watcher Converter on 1.20+
  gradle.properties
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/mc/entity/BukkitDataWatcherConverter.java
Labels: bug, size/M

#143 fix: Fixed OBCClassResolver for future paper (relocation removal.)
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/nms/BukkitNMSManagerImpl.java
  io.fairyproject.platforms/bukkit-platform/src/main/java/io/fairyproject/bukkit/version/OBCVersionDecoderImpl.java
Labels: enhancement, size/S

#145 feat(gui): Added updateTitle() method
  gradle.properties
  io.fairyproject.modules/platform.bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/Gui.java
Labels: size/S

#147 Improve the ModPageGuiSlot to allow for a consumer.
  gradle.properties
  io.fairyproject.modules/platform.bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/slot/GuiSlot.java
  io.fairyproject.modules/platform.bukkit/bukkit-gui/src/main/java/io/fairyproject/bukkit/gui/slot/ModPageGuiSlot.java
Labels: size/M
