Repository FairyProject/fairy, pull requests merged in 2025-03, with the labels that each got.

#179 feat: add support for configuration cache
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/extension/FairyExtension.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/FairyResource.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/FairyResourceAction.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/FairyResourcePlugin.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/impl/FairyResourceBukkitMeta.kt
  gradle-plugin/src/main/kotlin/io/fairyproject/gradle/resource/impl/FairyResourcePluginMeta.kt
Labels: size/L

#180 fix: #121
  framework/modules/bukkit/bukkit-items/src/main/java/io/fairyproject/bukkit/util/items/impl/ItemBuilderImpl.java
Labels: size/XS

#181 feat: enhance ContainerObjectBinder with TypeDescriptor support
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/binder/ContainerObjectBinder.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/binder/ContainerObjectBinderImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/node/loader/ContainerNodeLoader.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/ContainerObj.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/ContainerObjImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/provider/ConstructorInstanceProvider.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/provider/MethodInvokeInstanceProvider.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/resolver/ContainerObjectFactory.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/resolver/ContainerObjectResolver.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/object/resolver/ContainerObjectResolverImpl.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/processor/injection/AutowiredAnnotationProcessor.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/type/TypeDescriptor.java
  framework/platforms/core-platform/src/main/java/io/fairyproject/container/util/GenericTypeUtils.java
  framework/platforms/core-platform/src/test/java/io/fairyproject/container/GenericDependencyInjectionTest.java
Labels: size/XL
